# Generated by Django 5.1.4 on 2026-05-17 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("galleries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("original_file", models.CharField(max_length=500)),
                ("watermarked_file", models.CharField(blank=True, max_length=500)),
                ("thumbnail_file", models.CharField(blank=True, max_length=500)),
                ("filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=50)),
                ("size", models.PositiveIntegerField(help_text="File size in bytes")),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Aguardando processamento"),
                            ("processing", "Processando"),
                            ("ready", "Pronto"),
                            ("error", "Erro"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_error", models.TextField(blank=True)),
                ("celery_task_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("is_purchased", models.BooleanField(db_index=True, default=False)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="galleries.gallery",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto",
                "verbose_name_plural": "Fotos",
                "db_table": "photos",
                "ordering": ["sort_order", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PhotoFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="photos.photo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "photo_favorites",
            },
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["gallery", "status", "deleted_at"], name="photos_gallery_94eeac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(fields=["gallery", "sort_order"], name="photos_gallery_7fca8d_idx"),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["status", "celery_task_id"], name="photos_status_e47cbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photofavorite",
            index=models.Index(fields=["user", "photo"], name="photo_favor_user_id_4e5e97_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="photofavorite",
            unique_together={("user", "photo")},
        ),
    ]
